//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideShowHelperEN {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JPStringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JPStringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlideShowHelperEN.JPStringTable", typeof(JPStringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0]\nstart=1\nend={0,0:D}\nlayer=1\noverlay=1\ncamera=0\n[0.0]\n_name=図形\nサイズ=100\n縦横比=0.0\nライン幅=4000\ntype=0\ncolor={1}\nname=\n[0.1]\n_name=標準描画\nX=0.0\nY=0.0\nZ=0.0\n拡大率=100.00\n透明度=0.0\n回転=0.00\nblend=0\n.
        /// </summary>
        internal static string IDS_Bg {
            get {
                return ResourceManager.GetString("IDS_Bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start={0,0:D}\nend={1,0:D}\nlayer={2,0:D}\noverlay=1\ncamera=0\n.
        /// </summary>
        internal static string IDS_ImgCommon {
            get {
                return ResourceManager.GetString("IDS_ImgCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=画像ファイル\nfile={0}\n.
        /// </summary>
        internal static string IDS_ImgFile {
            get {
                return ResourceManager.GetString("IDS_ImgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=アニメーション効果\ntrack0={0,0:F2}\ntrack1={1,0:F2}\ntrack2=0.00,{2,0:F2},103\ntrack3=0.00,0.00,103\ncheck0=0\ntype=0\nfilter=2\nname=簡易ワープV2\nparam=local ATp={3,0:D};local DFp={4,0:D};local POS=1;local M=30;local BS=0;local PSA=0;local mcol=0xff0000;local acol=0x00ff00;local dcol=0x0000ff;local fcol=0xff00ff;local sz=50;local lw=3;\n.
        /// </summary>
        internal static string IDS_ImgFX {
            get {
                return ResourceManager.GetString("IDS_ImgFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=標準描画\nX=0.0\nY=0.0\nZ=0.0\n拡大率=100.00\n透明度=0.0\n回転=0.00\nblend=0\n.
        /// </summary>
        internal static string IDS_ImgStdDrawing {
            get {
                return ResourceManager.GetString("IDS_ImgStdDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width={0,0:D}\nheight={1,0:D}\nrate={2,0:D}\nscale={3,0:D}\nlength={4,0:D}\naudio_rate={5,0:D}\naudio_ch=2\n.
        /// </summary>
        internal static string IDS_PrjData {
            get {
                return ResourceManager.GetString("IDS_PrjData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start={0,0:D}\nend={1,0:D}\nlayer={2,0:D}\n.
        /// </summary>
        internal static string IDS_ScCommon {
            get {
                return ResourceManager.GetString("IDS_ScCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=シーンチェンジ\n調整=0.00\ntrack1=0.00\n反転=0\ncheck0=0\ntype={0,0:D}\nfilter=0\nname=\nparam=*\n.
        /// </summary>
        internal static string IDS_ScParam {
            get {
                return ResourceManager.GetString("IDS_ScParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=動画ファイル\n再生位置=1\n再生速度=100.0\nループ再生=1\nアルファチャンネルを読み込む=0\nfile={0}\n.
        /// </summary>
        internal static string IDS_VidFile {
            get {
                return ResourceManager.GetString("IDS_VidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語EXO.
        /// </summary>
        internal static string lblAsJp {
            get {
                return ResourceManager.GetString("lblAsJp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動画として読み込む.
        /// </summary>
        internal static string lblAsVideo {
            get {
                return ResourceManager.GetString("lblAsVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音声レート.
        /// </summary>
        internal static string lblAudRate {
            get {
                return ResourceManager.GetString("lblAudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景色.
        /// </summary>
        internal static string lblBG {
            get {
                return ResourceManager.GetString("lblBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開く.
        /// </summary>
        internal static string lblBrowse {
            get {
                return ResourceManager.GetString("lblBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 桁.
        /// </summary>
        internal static string lblDigits {
            get {
                return ResourceManager.GetString("lblDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像長さ.
        /// </summary>
        internal static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXO保存先.
        /// </summary>
        internal static string lblEXO {
            get {
                return ResourceManager.GetString("lblEXO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像フォルダ.
        /// </summary>
        internal static string lblFolder {
            get {
                return ResourceManager.GetString("lblFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フレームレート.
        /// </summary>
        internal static string lblFPS {
            get {
                return ResourceManager.GetString("lblFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フレーム.
        /// </summary>
        internal static string lblFrameUnit {
            get {
                return ResourceManager.GetString("lblFrameUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高さ.
        /// </summary>
        internal static string lblHeight {
            get {
                return ResourceManager.GetString("lblHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像枚数.
        /// </summary>
        internal static string lblImgCount {
            get {
                return ResourceManager.GetString("lblImgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柄の最大種類.
        /// </summary>
        internal static string lblMaxPatt {
            get {
                return ResourceManager.GetString("lblMaxPatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名の接頭.
        /// </summary>
        internal static string lblPrefix {
            get {
                return ResourceManager.GetString("lblPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シーンチェンジ柄の無差別化.
        /// </summary>
        internal static string lblRandom {
            get {
                return ResourceManager.GetString("lblRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シーンチェンジ物件.
        /// </summary>
        internal static string lblSC {
            get {
                return ResourceManager.GetString("lblSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 簡易ワープV2.
        /// </summary>
        internal static string lblSimpleWrap {
            get {
                return ResourceManager.GetString("lblSimpleWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名の接尾.
        /// </summary>
        internal static string lblSuffix {
            get {
                return ResourceManager.GetString("lblSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 転換長さ.
        /// </summary>
        internal static string lblTransDur {
            get {
                return ResourceManager.GetString("lblTransDur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幅.
        /// </summary>
        internal static string lblWidth {
            get {
                return ResourceManager.GetString("lblWidth", resourceCulture);
            }
        }
    }
}
