//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideShowHelperEN {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlideShowHelperEN.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0]\nstart=1\nend={0,0:D}\nlayer=1\noverlay=1\ncamera=0\n[0.0]\n_name=Graphic\nSize=100\nrAspect=0.0\nLine width=4000\ntype=0\ncolor={1}\nname=\n[0.1]\n_name=Standard drawing\nX=0.0\nY=0.0\nZ=0.0\nZoom%=100.00\nClearness=0.0\nRotation=0.00\nblend=0\n.
        /// </summary>
        internal static string IDS_Bg {
            get {
                return ResourceManager.GetString("IDS_Bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start={0,0:D}\nend={1,0:D}\nlayer={2,0:D}\noverlay=1\ncamera=0\n.
        /// </summary>
        internal static string IDS_ImgCommon {
            get {
                return ResourceManager.GetString("IDS_ImgCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=Image file\nfile={0}\n.
        /// </summary>
        internal static string IDS_ImgFile {
            get {
                return ResourceManager.GetString("IDS_ImgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=Animation effect\ntrack0={0,0:F2}\ntrack1={1,0:F2}\ntrack2=0.00,{2,0:F2},103\ntrack3=0.00,0.00,103\ncheck0=0\ntype=0\nfilter=2\nname=SimpleWrapV2\nparam=local ATp={3,0:D};local DFp={4,0:D};local POS=1;local M=30;local BS=0;local PSA=0;local mcol=0xff0000;local acol=0x00ff00;local dcol=0x0000ff;local fcol=0xff00ff;local sz=50;local lw=3;\n.
        /// </summary>
        internal static string IDS_ImgFX {
            get {
                return ResourceManager.GetString("IDS_ImgFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=Standard drawing\nX=0.0\nY=0.0\nZ=0.0\nZoom%=100.00\nClearness=0.0\nRotation=0.00\nblend=0\n.
        /// </summary>
        internal static string IDS_ImgStdDrawing {
            get {
                return ResourceManager.GetString("IDS_ImgStdDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width={0,0:D}\nheight={1,0:D}\nrate={2,0:D}\nscale={3,0:D}\nlength={4,0:D}\naudio_rate={5,0:D}\naudio_ch=2\n.
        /// </summary>
        internal static string IDS_PrjData {
            get {
                return ResourceManager.GetString("IDS_PrjData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start={0,0:D}\nend={1,0:D}\nlayer={2,0:D}\n.
        /// </summary>
        internal static string IDS_ScCommon {
            get {
                return ResourceManager.GetString("IDS_ScCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=Scene change\nAdjustment=0.00\ntrack1=0.00\nReversal=0\ncheck0=0\ntype={0,0:D}\nfilter=0\nname=\nparam=*\n.
        /// </summary>
        internal static string IDS_ScParam {
            get {
                return ResourceManager.GetString("IDS_ScParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _name=Video file\nPlayback position=1\nvPlay=100.0\nLoop playback=1\nImport alpha channel=0\nfile={0}\n.
        /// </summary>
        internal static string IDS_VidFile {
            get {
                return ResourceManager.GetString("IDS_VidFile", resourceCulture);
            }
        }
    }
}
